/**
 * Vendored types from @google/genai v2.15.0
 *
 * These enums are copied locally to keep the client library lightweight.
 * Update when @google/genai changes significantly.
 *
 * @see https://github.com/googleapis/js-genai/blob/main/src/types.ts
 */

/** Outcome of the code execution. */
export enum Outcome {
  /**
   * Unspecified status. This value should not be used.
   */
  OUTCOME_UNSPECIFIED = "OUTCOME_UNSPECIFIED",
  /**
   * Code execution completed successfully. `output` contains the stdout, if any.
   */
  OUTCOME_OK = "OUTCOME_OK",
  /**
   * Code execution failed. `output` contains the stderr and stdout, if any.
   */
  OUTCOME_FAILED = "OUTCOME_FAILED",
  /**
   * Code execution ran for too long, and was cancelled. There may or may not be a partial `output` present.
   */
  OUTCOME_DEADLINE_EXCEEDED = "OUTCOME_DEADLINE_EXCEEDED",
}

/** Programming language of the `code`. */
export enum Language {
  /**
   * Unspecified language. This value should not be used.
   */
  LANGUAGE_UNSPECIFIED = "LANGUAGE_UNSPECIFIED",
  /**
   * Python >= 3.10, with numpy and simpy available.
   */
  PYTHON = "PYTHON",
}

/** Specifies how the response should be scheduled in the conversation. Only applicable to NON_BLOCKING function calls, is ignored otherwise. Defaults to WHEN_IDLE. */
export enum FunctionResponseScheduling {
  /**
   * This value is unused.
   */
  SCHEDULING_UNSPECIFIED = "SCHEDULING_UNSPECIFIED",
  /**
   * Only add the result to the conversation context, do not interrupt or trigger generation.
   */
  SILENT = "SILENT",
  /**
   * Add the result to the conversation context, and prompt to generate output without interrupting ongoing generation.
   */
  WHEN_IDLE = "WHEN_IDLE",
  /**
   * Add the result to the conversation context, interrupt ongoing generation and prompt to generate output.
   */
  INTERRUPT = "INTERRUPT",
}

/** Output only. The reason why the model stopped generating tokens.

If empty, the model has not stopped generating the tokens. */
export enum FinishReason {
  /**
   * The finish reason is unspecified.
   */
  FINISH_REASON_UNSPECIFIED = "FINISH_REASON_UNSPECIFIED",
  /**
   * Token generation reached a natural stopping point or a configured stop sequence.
   */
  STOP = "STOP",
  /**
   * Token generation reached the configured maximum output tokens.
   */
  MAX_TOKENS = "MAX_TOKENS",
  /**
   * Token generation stopped because the content potentially contains safety violations. NOTE: When streaming, [content][] is empty if content filters blocks the output.
   */
  SAFETY = "SAFETY",
  /**
   * The token generation stopped because of potential recitation.
   */
  RECITATION = "RECITATION",
  /**
   * The token generation stopped because of using an unsupported language.
   */
  LANGUAGE = "LANGUAGE",
  /**
   * All other reasons that stopped the token generation.
   */
  OTHER = "OTHER",
  /**
   * Token generation stopped because the content contains forbidden terms.
   */
  BLOCKLIST = "BLOCKLIST",
  /**
   * Token generation stopped for potentially containing prohibited content.
   */
  PROHIBITED_CONTENT = "PROHIBITED_CONTENT",
  /**
   * Token generation stopped because the content potentially contains Sensitive Personally Identifiable Information (SPII).
   */
  SPII = "SPII",
  /**
   * The function call generated by the model is invalid.
   */
  MALFORMED_FUNCTION_CALL = "MALFORMED_FUNCTION_CALL",
  /**
   * Token generation stopped because generated images have safety violations.
   */
  IMAGE_SAFETY = "IMAGE_SAFETY",
  /**
   * The tool call generated by the model is invalid.
   */
  UNEXPECTED_TOOL_CALL = "UNEXPECTED_TOOL_CALL",
  /**
   * Image generation stopped because the generated images have prohibited content.
   */
  IMAGE_PROHIBITED_CONTENT = "IMAGE_PROHIBITED_CONTENT",
  /**
   * The model was expected to generate an image, but none was generated.
   */
  NO_IMAGE = "NO_IMAGE",
  /**
   * Image generation stopped because the generated image may be a recitation from a source.
   */
  IMAGE_RECITATION = "IMAGE_RECITATION",
  /**
   * Image generation stopped for a reason not otherwise specified.
   */
  IMAGE_OTHER = "IMAGE_OTHER",
}

/** Output only. The traffic type for this request. This enum is not supported in Gemini API. */
export enum TrafficType {
  /**
   * Unspecified request traffic type.
   */
  TRAFFIC_TYPE_UNSPECIFIED = "TRAFFIC_TYPE_UNSPECIFIED",
  /**
   * The request was processed using Pay-As-You-Go quota.
   */
  ON_DEMAND = "ON_DEMAND",
  /**
   * Type for Priority Pay-As-You-Go traffic.
   */
  ON_DEMAND_PRIORITY = "ON_DEMAND_PRIORITY",
  /**
   * Type for Flex traffic.
   */
  ON_DEMAND_FLEX = "ON_DEMAND_FLEX",
  /**
   * Type for Provisioned Throughput traffic.
   */
  PROVISIONED_THROUGHPUT = "PROVISIONED_THROUGHPUT",
}

/** The modality that this token count applies to. */
export enum MediaModality {
  /**
   * When a modality is not specified, it is treated as `TEXT`.
   */
  MODALITY_UNSPECIFIED = "MODALITY_UNSPECIFIED",
  /**
   * The `Part` contains plain text.
   */
  TEXT = "TEXT",
  /**
   * The `Part` contains an image.
   */
  IMAGE = "IMAGE",
  /**
   * The `Part` contains a video.
   */
  VIDEO = "VIDEO",
  /**
   * The `Part` contains audio.
   */
  AUDIO = "AUDIO",
  /**
   * The `Part` contains a document, such as a PDF.
   */
  DOCUMENT = "DOCUMENT",
}
